---
title: 'Retail Sales, Bloomberg Economic Calender'
author: 'Riley Roach'
date: '05/02/2018'
output: 
  pdf_document: 
    latex_engine: xelatex
---

1. Retail Sales
==================================
On April 16th of this year, the U.S. Bureau of the Census released information for the Market Moving Indicator, Retail Sales, collected during the Monthly Retail Trade Survey. Since Retail Sales account for more than half of the U.S. economy, the indicator is of particular importance. Business performance, at the end of the day, depends on consumers purchasing products. Reportings of low figures may cause concern for investors.


2. Reported Figures
==================================
Prior to the release, Retail Sales were reported to be **-0.1%**. A rise of **0.2%** is observed when removing statistics for automobiles, and an additional increase of **0.3%** is seen when removing gasoline as well.

The realized figures for the release reported as **0.6%**, **0.2%**, and **0.3%**. The data can be seen below.

```{r echo = FALSE, eval = TRUE, message = FALSE, error = FALSE}
library(tidyverse)

data <- tibble(
  `Measure` = c('Retail Sales - M/M',
              'Retail Sales less autos - M/M change',
              'Less Autos & Gas - M/M Change'),
  `Prior` = c('-0.1%',
              '0.2%',
              '0.3%'),
  `Actual` = c('0.6%',
               '0.2%',
               '0.3%')
)
library(kableExtra)
kable(head(data))
```


These numbers, while not large, represent a small increase in consumer spending, observed by the **Retail Sales - M/M changes** measure. Moreover, sales from autos, and sales from autos and gas, remain unchanged. The increase in **Retail Sales - M/M changes** can be explained by considering that consumers are spending the savings gained from autos and gas.




